apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: mlx-dpdk-node-policy-for-testpmd
  namespace: openshift-sriov-network-operator
spec:
  resourceName: mellanox_r640_cx5_25g
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  numVfs: 5
  mtu: 1500
  nicSelector:
    pfNames: ["ens3f1"]
    rootDevices: ["0000:d8:00.1"]
  deviceType: netdevice
  isRdma: true 
