apiVersion: v1
kind: Pod
metadata:
  name: pv-pod-for-qa
spec:
  securityContext: {}

  volumes:
    - name: pv-storage-for-qa
      persistentVolumeClaim:
        claimName: pv-claim-for-qa

  containers:
    - name: pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      securityContext:
          privileged: true
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pv-storage-for-qa

