apiVersion: v1
kind: Pod
metadata:
  name: testpmd-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: testpmd-sriov-network
spec:
  containers:
  - name: testpmd
    image: registry.redhat.io/openshift4/dpdk-base-rhel8:v4.6
    securityContext:
            #privileged: true
     allowPrivilegeEscalation: false
     runAsUser: 0
     capabilities:
        add: ["IPC_LOCK"]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      limits:
        memory: "1Gi"
        cpu: "6"
        hugepages-1Gi: "4Gi"
      requests:
        memory: "1Gi"
        cpu: "6"
        hugepages-1Gi: "4Gi"
    command: ["sleep", "infinity"]
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages


