apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: cmp2-sriov-network-170
  namespace: openshift-sriov-network-operator
spec:
  resourceName: mellanox_r640_cx5_25g
  networkNamespace: testns
  ipam: '{"type":"static","addresses": [{"address":"192.168.170.61/24", "gateway":"192.168.170.1"}],"routes": [{"dst":"192.168.50.0/24","gw":"192.168.170.1"}]}'
  vlan: 170
  capabilities: '{"mac": true, "ips": true}'

