apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: intel-sriov-network
  namespace: openshift-sriov-network-operator
spec:
  resourceName: intelnics
  networkNamespace: openshift-sriov-network-operator
  ipam: '{"type":"static","addresses": [{"address":"192.168.150.61/24", "gateway":"192.168.150.1"}],"routes": [{"dst":"192.168.50.0/24","gw":"192.168.150.1"}]}'
  capabilities: '{"mac": true, "ips": true}'

 

