---
apiVersion: v1
kind: Pod
metadata:
  name: compute-1-pod-dcdn
  namespace: testns
  annotations:
    k8s.v1.cni.cncf.io/networks: cmp1-sriov-network-150
spec:
  nodeSelector:
    kubernetes.io/hostname: cmp1.dsp.lab
  containers:
  - name: example-pod1
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools
---
apiVersion: v1
kind: Pod
metadata:
  name: compute-2-pod-dcdn
  namespace: testns
  annotations:
    k8s.v1.cni.cncf.io/networks: cmp2-sriov-network-170
spec:
  nodeSelector:
    kubernetes.io/hostname: cmp1.dsp.lab
  containers:
  - name: example-pod2
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools

